### ISSUE TITLE
백엔드 구조 논의

### ISSUE THREAD

**Issue by seongahjo** [Nexters/FALCON#14]
레이어를 결정합시다

1. repository를 명시적인 레이어로 분리할 것인가 
2. 가시성 결정

**Comment by BaeJi77** [comment]
> repository를 명시적인 레이어로 분리할 것인가

일단 domain에서 처리하도록. 나중에 리팩토링하면서 수정하는 방향을 생각.

> 가시성 결정

현재 모두 public으로 처리? 현재는 괜찮지만 의존성 문제로 모듈을 분리하게 되는 경우 가시성으로 명확하게 의존성을 제한할 수 있음.

`internal`로 하는경우 같은 모듈 내에서만 접근 가능함. 

`protected` 상속받은 애들만 접근만 가능함. 같은 패키지 내부에서도 접근 불가 (java와 차이점)

**Comment by BaeJi77** [comment]
일단 빠른 개발을 위해서 기능 구현을 위주로. 

코드 리뷰를 통해서 너무 안좋은 패턴이나 코드 형식을 보면 리뷰를 통해서 극복하도록.
