### ISSUE TITLE
Implement notification feature

### ISSUE THREAD

**Issue by BaeJi77** [Nexters/FALCON#24]
- [GET]  알람 가져오기
  - Notification 도메인 등록 필요
- notification 발생 -> 이벤트 발생시기에 notification handler 활용?

**Comment by tjdcks12** [comment]
Notification등록을 위한 도메인은 필요 (ASK 생성시 Notification 등록, 이후에 follower개념생기면 follower가 무슨 행동할때 Notification 등록 등...) 
블록체인에 생성된 이벤트나 트랜잭션을 트래킹하는 부분은 서버쪽에서 해야할지 점검은 필요할듯. (백엔드에서 blockchain 상태확인 하는 방식이 도입될수도.. 그때는 http://web3j.io/ 이거 참고)

**Comment by tjdcks12** [comment]
### 테이블 스키마

- notification_id (PK)
- user_id (FK) : 유저별 noti생성되므로
- type : 노티 종류
  - Ask (질문)
  - Transaction (판매관련)
- content : 노티 내용

**Comment by BaeJi77** [comment]
블록체인을 트래킹하기 보다는 프론트에서 요청을 받아서 처리하는 것은 어떨까?

블록체인 트래킹해서 하면 좋을텐데 사실 너무 많은 데이터를 트래킹해야될 수도 있고. cookie에 대한 정보도 서버에서 관리해야됨.

만약 구매를 했을 경우 (판매자에게는 판매) 이럴 경우 front 에서 서버 쪽으로 해당 정보를 보내주면 좋지 않을까?
