### ISSUE TITLE
쿠키 상세 화면 뷰 정의

### ISSUE THREAD

**Issue by seongahjo** [Nexters/FALCON#39]
쿠키 상세 화면 뷰에 필요한 데이터를 정의한다.

**Comment by BaeJi77** [comment]
우리 홈 화면 관련해서는 따로 api 개발 진행하면 되는건가? 알아서 짬뽕으로 가져가도록?

**Comment by seongahjo** [comment]
@BaeJi77 
놉 화면별로 API 하나씩 두는 게 좋을 것 같은데 어떰?
